// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// DTMbvs
List DTMbvs(int iterations, int thin, String prior, arma::mat x, arma::vec branch_location, List node_children_pointer, arma::mat branch_counts, arma::mat subtree_counts, arma::mat alpha, arma::cube phi, arma::cube zeta, double sigma2_alpha, double sigma2_phi, double aa, double bb, arma::cube Omega, arma::cube G, arma::cube Var, arma::mat S, double v0, double v1, double a_G, double b_G, double pie, double lambda);
RcppExport SEXP _DTMbvs_DTMbvs(SEXP iterationsSEXP, SEXP thinSEXP, SEXP priorSEXP, SEXP xSEXP, SEXP branch_locationSEXP, SEXP node_children_pointerSEXP, SEXP branch_countsSEXP, SEXP subtree_countsSEXP, SEXP alphaSEXP, SEXP phiSEXP, SEXP zetaSEXP, SEXP sigma2_alphaSEXP, SEXP sigma2_phiSEXP, SEXP aaSEXP, SEXP bbSEXP, SEXP OmegaSEXP, SEXP GSEXP, SEXP VarSEXP, SEXP SSEXP, SEXP v0SEXP, SEXP v1SEXP, SEXP a_GSEXP, SEXP b_GSEXP, SEXP pieSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< String >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type branch_location(branch_locationSEXP);
    Rcpp::traits::input_parameter< List >::type node_children_pointer(node_children_pointerSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type branch_counts(branch_countsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type subtree_counts(subtree_countsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type zeta(zetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_alpha(sigma2_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_phi(sigma2_phiSEXP);
    Rcpp::traits::input_parameter< double >::type aa(aaSEXP);
    Rcpp::traits::input_parameter< double >::type bb(bbSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type G(GSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Var(VarSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    Rcpp::traits::input_parameter< double >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< double >::type a_G(a_GSEXP);
    Rcpp::traits::input_parameter< double >::type b_G(b_GSEXP);
    Rcpp::traits::input_parameter< double >::type pie(pieSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(DTMbvs(iterations, thin, prior, x, branch_location, node_children_pointer, branch_counts, subtree_counts, alpha, phi, zeta, sigma2_alpha, sigma2_phi, aa, bb, Omega, G, Var, S, v0, v1, a_G, b_G, pie, lambda));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DTMbvs_DTMbvs", (DL_FUNC) &_DTMbvs_DTMbvs, 25},
    {NULL, NULL, 0}
};

RcppExport void R_init_DTMbvs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
